import UserSessionProvider from "./components/UserSessionProvider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserSessionProvider>
          {children}
        </UserSessionProvider>
      </body>
    </html>
  );
}